sonarr:
  series:
    base_url: http://sonarr:8989
    api_key: ${SONARR_API_KEY}

    include:
      - template: french-vostfr-bluray-web-1080p

    delete_old_custom_formats: true


radarr:
  movies:
    base_url: http://radarr:7878
    api_key: ${RADARR_API_KEY}

    include:
      - template: french-vostfr-hd-bluray-web

    delete_old_custom_formats: true
